# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="audio.mp3"
Content-Type: audio/mpeg

< ./audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/d8407d99-df62-44e6-89f0-975467b9023a/transcription
Content-Type: application/json

{
 "prompt": "music"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
 "videoId": "d8407d99-df62-44e6-89f0-975467b9023a",
 "temperature": 0.5,
 "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}
